#!/usr/bin/env node
// ============================================================
// stamp.js — cache-busting for a no-build ES-module app.
//
// GitHub Pages serves everything with `cache-control: max-age=600` and we
// cannot set response headers. A returning browser therefore happily runs a
// ten-minute-old build, which is indistinguishable from a broken deploy.
//
// Relative module specifiers do NOT inherit their importer's query string:
// resolving './solver.js' against '/src/app.js?v=abc' yields '/src/solver.js',
// no query. Stamping only index.html would refresh app.js while every module
// it imports stays stale — the worst possible half-fix. So every specifier
// gets stamped, including dynamic import() and the worker URL.
//
// Idempotent: existing ?v= stamps are stripped before hashing and rewriting,
// so the hash depends on real content, not on the previous stamp.
//
//   node tools/stamp.js          stamp with the content hash
//   node tools/stamp.js --check  exit 1 if stamps are stale (CI-friendly)
// ============================================================
import { createHash } from 'node:crypto';
import { readFileSync, writeFileSync, readdirSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const SRC = join(ROOT, 'src');

const STAMP_RE = /\?v=[0-9a-f]{8}/g;
const unstamp = (s) => s.replace(STAMP_RE, '');

// BUILD_ID is generated, so it must not feed its own hash.
const GENERATED = new Set(['build.js']);

const srcFiles = readdirSync(SRC).filter((f) => f.endsWith('.js') && !GENERATED.has(f)).sort();

function hashOf() {
  const h = createHash('sha1');
  for (const f of srcFiles) h.update(f).update(unstamp(readFileSync(join(SRC, f), 'utf8')));
  h.update('styles.css').update(readFileSync(join(ROOT, 'styles.css'), 'utf8'));
  h.update('index.html').update(unstamp(readFileSync(join(ROOT, 'index.html'), 'utf8')));
  return h.digest('hex').slice(0, 8);
}

const v = hashOf();

// Every way this app names another module, each capturing the specifier so the
// stamp lands inside the quotes.
const patterns = [
  /(\bfrom\s*['"])(\.\/[^'"]+?\.js)(['"])/g,          // static import ... from './x.js'
  /(\bimport\s*\(\s*['"])(\.\/[^'"]+?\.js)(['"])/g,   // dynamic import('./x.js')
  /(\bnew\s+URL\s*\(\s*['"])(\.\/[^'"]+?\.js)(['"])/g, // new URL('./x.worker.js', import.meta.url)
];

function stampJs(text) {
  let out = unstamp(text);
  for (const re of patterns) out = out.replace(re, (_m, a, spec, c) => `${a}${spec}?v=${v}${c}`);
  return out;
}

function stampHtml(text) {
  return unstamp(text)
    .replace(/(<script[^>]*\ssrc=")(\.\/src\/[^"]+?\.js)(")/g, (_m, a, s, c) => `${a}${s}?v=${v}${c}`)
    .replace(/(<link[^>]*\shref=")(\.\/styles\.css)(")/g, (_m, a, s, c) => `${a}${s}?v=${v}${c}`);
}

const buildJs = `// Generated by tools/stamp.js — do not edit.\nexport const BUILD_ID = '${v}';\n`;

const targets = [
  ...srcFiles.map((f) => ({ path: join(SRC, f), next: stampJs(readFileSync(join(SRC, f), 'utf8')) })),
  { path: join(SRC, 'build.js'), next: buildJs },
  { path: join(ROOT, 'index.html'), next: stampHtml(readFileSync(join(ROOT, 'index.html'), 'utf8')) },
];

const check = process.argv.includes('--check');
let changed = 0;
for (const t of targets) {
  let cur = '';
  try { cur = readFileSync(t.path, 'utf8'); } catch (e) {}
  if (cur === t.next) continue;
  changed++;
  if (!check) writeFileSync(t.path, t.next);
}

if (check && changed) {
  console.error(`stamp: ${changed} file(s) out of date — run: node tools/stamp.js`);
  process.exit(1);
}
console.log(`stamp: build ${v} · ${changed} file(s) ${check ? 'would change' : 'updated'}`);
